name: "Main"
on:
    push:
      branches:
        - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
jobs:

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build:
    name: deploy
    needs: [formatting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install --locked trunk
      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release -M --public-url=/
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.2.0
        with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
            working-directory: ./dist
            vercel-project-name: hello-sycamore
            vercel-args: --prod


